spring:
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: todorovich.local
          keystore:
            location: ./certs/todorovich.local.p12
            password: ""
            type: PKCS12
      pem:
        client:
          truststore:
            certificate: ./certs/todorovich.local.pem
  application:
    name: "server"
  data:
    mongodb:
      uri:  ""

server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: ./certs/todorovich.local.p12
    key-alias: todorovich.local
    key-store-password: ""
    trust-store: ./certs/todorovich.local.truststore
    trust-store-password: ""

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    net.todorovich: TRACE

okta:
  oauth2:
    issuer-uri: https://www.todorovich.local/
    issuer: https://dev-1nhpv0tsxpv8gwh4.us.auth0.com/
    client-id: ""
    client-secret: ""